#! /bin/sh

# This script is meant to only copy cfg/ and aux/ directories down South.
# That allows the quickest access to run meta data for monitoring.

DESTHOST=rnog-rsync.zeuthen.desy.de
DESTUSER=rnogtx
DESTDIR=/pnfs/ifh.de/acs/radio/diskonly/data/inbox
SRCDIR=/data/ingress
RATE=48  # kB/s  - FS: Increased it to accomodate fast transfer in presents of flower data
PERMS="Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r"
BLOCKSIZE="-B 512"

while true;
do
  # Rules are evaluated in order, first match wins: keep only top-level station*
  # directories (the "/" anchors the pattern at SRCDIR), then drop bulk data.
  rsync -P -avh --bwlimit=${RATE} --chmod=${PERMS} ${BLOCKSIZE} \
    --include "/station*/" --exclude "/*" \
    --exclude "*log.xz" --exclude "waveforms/" --exclude "header/" \
    --exclude "daqstatus/" --exclude "*dat.gz" --exclude "*tmp" --exclude "*.root" \
    ${SRCDIR}/ ${DESTUSER}@${DESTHOST}:${DESTDIR}

  echo "Sleep for 10s"
  sleep 10
done
